packages:
  - 'frontend'
  - 'backend'
  - 'packages/*'
allowBuilds:
  '@parcel/watcher': set this to true or false
  '@prisma/client': set this to true or false
  '@prisma/engines': set this to true or false
  argon2: set this to true or false
  esbuild: set this to true or false
  prisma: set this to true or false
  unrs-resolver: set this to true or false
minimumReleaseAgeExclude:
  - '@types/node@22.20.3'
  - framer-motion@13.4.0
